version: "3.7"

services:
  mongodb:
    container_name: mongodb
    image: mongo:4.1
    ports:
      - 27017:27017
    networks:
      - project_nodejs
  app_project:
    container_name: NodeJsExpressAPpMongoDb
    build:
      context: .
      dockerfile: Dockerfile
    image: projectnodejsexpressmongo:1.0
    ports:
      - 3000:3000
    links:
      - mongodb
    depends_on:
      - mongodb
    networks:
      - project_nodejs

networks:
  project_nodejs:
    name: project_nodejs

